'use strict';(()=>{
const $=s=>document.querySelector(s), TAU=Math.PI*2, canvas=$('#canvas'), ctx=canvas.getContext('2d');
const LEVELS=[{name:'PULSO PRIME',difficulty:'FÁCIL',speed:320,length:10500,colors:['#2ee9ff','#ff47d2'],pattern:0},{name:'VIA CROMA',difficulty:'FÁCIL',speed:340,length:11500,colors:['#a8ff4d','#34d7ff'],pattern:1},{name:'GRAVIDADE ZERO',difficulty:'NORMAL',speed:360,length:12800,colors:['#8b7cff','#ff5ccf'],pattern:2},{name:'RITMO BRUTO',difficulty:'DIFÍCIL',speed:380,length:14200,colors:['#ff7b55','#ffd34d'],pattern:3},{name:'PULSO FINAL',difficulty:'EXTREMA',speed:400,length:15800,colors:['#ff47d2','#4e8dff'],pattern:4}];
const SAVE_KEY='neon_rush_v6_save'; const save=(()=>{const d={unlocked:1,best:Array(LEVELS.length).fill(0),wins:Array(LEVELS.length).fill(false),coins:Array(LEVELS.length).fill(0)};try{return Object.assign(d,JSON.parse(localStorage.getItem(SAVE_KEY)||'{}'))}catch{return d}})();
let W=1280,H=720,dpr=1;function resize(){const r=canvas.getBoundingClientRect();W=Math.max(900,r.width);H=Math.max(520,r.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
let audio=null;function unlockAudio(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}catch{}}function beep(freq=440,d=.05,type='square',gain=.025){if(!audio)return;try{const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
const input={held:false,pressed:false,dash:false}; addEventListener('keydown',e=>{if([' ','w','W','ArrowUp'].includes(e.key)){e.preventDefault();input.pressed=true;input.held=true;unlockAudio()}if(['Shift','x','X'].includes(e.key)){e.preventDefault();input.dash=true;unlockAudio()}if(e.key==='Escape'&&world.active)togglePause();if((e.key==='r'||e.key==='R')&&world.active)restart()});addEventListener('keyup',e=>{if([' ','w','W','ArrowUp'].includes(e.key))input.held=false});canvas.addEventListener('pointerdown',e=>{e.preventDefault();input.pressed=true;input.held=true;unlockAudio()},{passive:false});addEventListener('pointerup',()=>input.held=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
const world={active:false,paused:false,level:0,t:0,camera:0,ground:0,player:null,objects:[],rings:[],particles:[],shake:0,flash:0,collected:0,score:0,dead:false,deadTimer:0};
function playerBox(){const p=world.player;return{x:145-17,y:p.y-17,w:34,h:34}}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function addSpike(x,count=1){for(let i=0;i<count;i++)world.objects.push({type:'spike',x:x+i*34,w:34,h:46})}
function addBlock(x,w=90,h=70){world.objects.push({type:'block',x,w,h,y:world.ground-h})}
function addRing(x,y,big=false){world.rings.push({x,y,big,taken:false,spin:Math.random()*TAU})}
function buildLevel(i){const L=LEVELS[i];world.level=i;world.active=true;world.paused=false;world.t=0;world.camera=0;world.ground=H*.78;world.player={y:world.ground-17,vy:0,rot:0,onGround:true,trail:[]};world.objects=[];world.rings=[];world.particles=[];world.shake=0;world.flash=0;world.collected=0;world.score=0;world.dead=false;world.deadTimer=0;
 let x=720;
 // Large opening runway, then hand-authored sections. Level 1 is intentionally forgiving and fully hold-safe.
 if(i===0){
   const gaps=[300,330,345,320,355,340,370,350,360,335,365,345,380,350,370,355,365,340];
   for(let k=0;k<gaps.length;k++){addRing(x+55,world.ground-120-(k%3)*14,k%6===0);addSpike(x,1);if(k%4===1)addRing(x+85,world.ground-185,true);x+=gaps[k]}
 } else {
   const patterns=[()=>{addSpike(x);addRing(x+60,world.ground-125);x+=320},()=>{addSpike(x,2);addRing(x+80,world.ground-150,true);x+=350},()=>{addBlock(x,110,70);addRing(x+55,world.ground-150);x+=380},()=>{addSpike(x);addSpike(x+95);addRing(x+52,world.ground-165,true);x+=390},()=>{addBlock(x,130,90);addSpike(x+48);addRing(x+68,world.ground-170);x+=410}];while(x<L.length-700){patterns[Math.floor((world.t*1000+x)%patterns.length)]()}
 }
 addRing(L.length-360,world.ground-155,true);$('#levelName').textContent=`FASE ${i+1} — ${L.name}`;$('#hint').textContent=i===0?'SEGURE ESPAÇO OU CLIQUE PARA AUTO-PULAR':'SEGURE PARA ENCADEAR OS PULOS';updateHUD()
}
function burst(x,y,col,n=14){if(!$('#particleToggle').checked)return;for(let i=0;i<n;i++){const a=Math.random()*TAU,s=80+Math.random()*250;world.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.4,size:2+Math.random()*4,col})}}
function die(){if(world.dead)return;world.dead=true;world.deadTimer=.65;world.flash=.45;world.shake=12;burst(145,world.player.y,'#ff3b80',42);if($('#fxToggle').checked)beep(110,.18,'sawtooth',.05)}
function restart(){hide('#pause');hide('#result');buildLevel(world.level)}
function win(){world.active=false;const i=world.level;save.best[i]=100;save.wins[i]=true;save.coins[i]=Math.max(save.coins[i]||0,world.collected);save.unlocked=Math.max(save.unlocked,Math.min(LEVELS.length,i+2));try{localStorage.setItem(SAVE_KEY,JSON.stringify(save))}catch{}$('#resultText').textContent=`100% concluído • ${world.collected} coletáveis • ${world.score} pontos`;showModal('#result');if($('#fxToggle').checked){beep(660,.08);setTimeout(()=>beep(880,.1),90);setTimeout(()=>beep(1100,.14),180)}}
function update(dt){if(!world.active||world.paused)return;if(world.dead){world.deadTimer-=dt;world.flash=Math.max(0,world.flash-dt);updateParticles(dt);if(world.deadTimer<=0)restart();return}const L=LEVELS[world.level],p=world.player;world.t+=dt;world.shake=Math.max(0,world.shake-dt*30);world.flash=Math.max(0,world.flash-dt);world.camera+=L.speed*dt*(p.dash?1.6:1);p.vy+=2200*dt;
 if((input.pressed||input.held)&&p.onGround){input.pressed=false;p.vy=-780;p.onGround=false;world.flash=.06;world.shake=Math.max(world.shake,2);burst(145,p.y,'#2ee9ff',8);if($('#fxToggle').checked)beep(520,.04)}
 if(input.dash&&!p.dash){input.dash=true;setTimeout(()=>input.dash=false,190);world.shake=8;burst(145,p.y,'#ff47d2',20);if($('#fxToggle').checked)beep(760,.06,'sawtooth',.03)}
 p.y+=p.vy*dt;if(p.y>=world.ground-17){p.y=world.ground-17;p.vy=0;p.onGround=true}else p.onGround=false;
 if(p.y>H+40)die();p.rot+=(p.onGround?0:7.8)*dt;
 const pr=playerBox();for(const o of world.objects){const rr={x:o.x-world.camera+145,y:o.y??world.ground-o.h,w:o.w,h:o.h};if(rr.x<220&&rr.x+rr.w>95&&hit(pr,rr)){die();break}}
 for(const r of world.rings){if(r.taken)continue;const sx=r.x-world.camera+145;if(Math.abs(sx-145)<30&&Math.abs(r.y-p.y)<40){r.taken=true;world.collected++;world.score+=r.big?500:100;burst(sx,r.y,L.colors[1],12);if($('#fxToggle').checked)beep(r.big?1040:820,.04)}}
 if(world.camera>=L.length){win();return}updateParticles(dt);updateHUD();p.trail.push({x:145,y:p.y});if(p.trail.length>10)p.trail.shift()}
function updateParticles(dt){for(const p of world.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=520*dt;p.life-=dt}world.particles=world.particles.filter(p=>p.life>0)}
function draw(){const L=LEVELS[world.level];const ox=world.shake?(Math.random()-.5)*world.shake:0,oy=world.shake?(Math.random()-.5)*world.shake:0;ctx.save();ctx.translate(ox,oy);drawBg(L);drawTrack(L);drawObjects(L);drawRings(L);drawPlayer(L);drawParticles();ctx.restore();if(world.flash>0){ctx.fillStyle=`rgba(255,255,255,${world.flash*.35})`;ctx.fillRect(0,0,W,H)}}
function drawBg(L){ctx.fillStyle='#050713';ctx.fillRect(0,0,W,H);ctx.globalAlpha=.18;ctx.strokeStyle=L.colors[0];ctx.lineWidth=1;const gx=-((world.camera*.32)%80),gy=90;for(let x=gx;x<W+80;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+20,H);ctx.stroke()}for(let y=gy;y<H;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.globalAlpha=1;for(let i=0;i<10;i++){const x=((i*180-world.camera*.07)%(W+240))-120,h=70+(i%5)*28;ctx.fillStyle=i%2?'#0b1330':'#0d1738';ctx.fillRect(x,world.ground-90-h,90,h);ctx.fillRect(x+25,world.ground-112-h,34,22)}ctx.globalAlpha=.08+Math.sin(world.t*8)*.02;ctx.fillStyle=L.colors[0];ctx.beginPath();ctx.arc(W*.55,H*.33,250,0,TAU);ctx.fill();ctx.globalAlpha=1}
function drawTrack(L){ctx.fillStyle='#121d3a';ctx.fillRect(0,world.ground,W,H-world.ground);ctx.strokeStyle=L.colors[0];ctx.lineWidth=3;for(let x=-((world.camera*.9)%60);x<W;x+=60){ctx.beginPath();ctx.moveTo(x,world.ground);ctx.lineTo(x-55,H);ctx.stroke()}ctx.fillStyle='#253761';ctx.fillRect(0,world.ground-4,W,4)}
function drawObjects(L){for(const o of world.objects){const x=o.x-world.camera+145;if(x<-70||x>W+70)continue;if(o.type==='spike'){ctx.save();ctx.shadowColor=L.colors[1];ctx.shadowBlur=14;ctx.fillStyle=L.colors[1];ctx.beginPath();ctx.moveTo(x,world.ground);ctx.lineTo(x+o.w/2,world.ground-o.h);ctx.lineTo(x+o.w,world.ground);ctx.closePath();ctx.fill();ctx.restore()}else{const y=o.y;ctx.fillStyle='#0d1731';ctx.fillRect(x,y,o.w,o.h);ctx.strokeStyle=L.colors[0];ctx.lineWidth=3;ctx.strokeRect(x+1.5,y+1.5,o.w-3,o.h-3);ctx.globalAlpha=.2;ctx.fillStyle=L.colors[0];ctx.fillRect(x+9,y+9,o.w-18,8);ctx.globalAlpha=1}}}
function drawRings(L){for(const r of world.rings){if(r.taken)continue;const x=r.x-world.camera+145;if(x<-40||x>W+40)continue;const rr=r.big?14:10;ctx.save();ctx.translate(x,r.y);ctx.rotate(world.t*2+r.spin);ctx.strokeStyle=L.colors[1];ctx.lineWidth=4;ctx.shadowColor=L.colors[1];ctx.shadowBlur=16;ctx.beginPath();ctx.arc(0,0,rr,0,TAU);ctx.stroke();ctx.restore()}}
function drawPlayer(L){const p=world.player;for(let i=0;i<p.trail.length;i++){const t=p.trail[i],a=i/p.trail.length*.18;ctx.globalAlpha=a;ctx.fillStyle=L.colors[0];ctx.fillRect(t.x-13,t.y-13,26,26)}ctx.globalAlpha=1;ctx.save();ctx.translate(145,p.y);ctx.rotate(p.rot);ctx.shadowColor=L.colors[0];ctx.shadowBlur=24;const s=38,d=7;ctx.fillStyle='#f9fbff';ctx.fillRect(-s/2,-s/2,s,s);ctx.fillStyle='#ccd6e5';ctx.beginPath();ctx.moveTo(s/2,-s/2);ctx.lineTo(s/2+d,-s/2+d);ctx.lineTo(s/2+d,s/2-d);ctx.lineTo(s/2,s/2);ctx.closePath();ctx.fill();ctx.fillStyle='#b8c4d5';ctx.beginPath();ctx.moveTo(-s/2,s/2);ctx.lineTo(s/2,s/2);ctx.lineTo(s/2+d,s/2-d);ctx.lineTo(-s/2+d,s/2-d);ctx.closePath();ctx.fill();ctx.strokeStyle=L.colors[0];ctx.lineWidth=3;ctx.strokeRect(-s/2+1.5,-s/2+1.5,s-3,s-3);ctx.fillStyle=L.colors[1];ctx.fillRect(-9,-9,18,18);ctx.fillStyle='#071126';ctx.fillRect(-10,-5,6,6);ctx.fillRect(4,-5,6,6);ctx.restore()}
function drawParticles(){for(const p of world.particles){ctx.globalAlpha=Math.max(0,p.life/.65);ctx.fillStyle=p.col;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1}
function updateHUD(){const L=LEVELS[world.level],pct=Math.min(100,Math.floor(world.camera/L.length*100));$('#bar').style.width=pct+'%';$('#pct').textContent=pct+'%';$('#coins').textContent=world.collected;$('#score').textContent=world.score}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.add('hidden'));$('#'+id).classList.remove('hidden')}function showModal(sel){$(sel).classList.remove('hidden')}function hide(sel){$(sel).classList.add('hidden')}function togglePause(){if(!world.active)return;world.paused=!world.paused;$('#pause').classList.toggle('hidden',!world.paused)}
function renderLevels(){const g=$('#levelGrid');g.innerHTML='';LEVELS.forEach((L,i)=>{const open=i<save.unlocked;const c=document.createElement('article');c.className='level-card'+(open?'':' locked');c.innerHTML=`<div><div class="num">${String(i+1).padStart(2,'0')}</div><h3>${L.name}</h3><p>${L.difficulty} • ${Math.round(L.speed)} px/s</p></div><div><small>MELHOR ${save.best[i]||0}% • ◆ ${save.coins[i]||0}</small><button class="${open?'primary':''}" ${open?'':'disabled'}>${open?'JOGAR':'BLOQUEADA'}</button></div>`;if(open)c.querySelector('button').onclick=()=>startLevel(i);g.appendChild(c)});$('#saveInfo').textContent=`${save.wins.filter(Boolean).length}/${LEVELS.length} concluídas`}
function startLevel(i){unlockAudio();show('game');requestAnimationFrame(()=>{resize();buildLevel(i)})}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;unlockAudio();if(a==='play')startLevel(Math.max(0,Math.min(save.unlocked-1,LEVELS.length-1)));else if(a==='levels'){world.active=false;hide('#pause');hide('#result');renderLevels();show('levels')}else if(a==='settings')show('settings');else if(a==='menu'){world.active=false;hide('#pause');hide('#result');show('menu')}else if(a==='pause')togglePause();else if(a==='resume')togglePause();else if(a==='restart')restart();else if(a==='reset'){try{localStorage.removeItem(SAVE_KEY)}catch{}location.reload()}});$('#next').onclick=()=>{hide('#result');if(world.level+1<LEVELS.length)startLevel(world.level+1);else{renderLevels();show('levels')}};
let last=performance.now();function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}renderLevels();show('menu');requestAnimationFrame(loop);
})();
